<?php
/**
 * EnumAcquiringServicesCode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Acquiring Services - Open Finance Brasil
 *
 * API de Credenciamento do Open Finance Brasil – Fase 4. API que retorna informações de Credenciamento.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EnumAcquiringServicesCode Class Doc Comment
 *
 * @category Class
 * @description Sigla da Tarifa cobrada sobre o Serviço de Credenciamento informado.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Uacquiring-servicesEnumAcquiringServicesCode
{
    /**
     * Possible values of this enum
     */
    public const MDR_CREDITO = 'MDR_CREDITO';

    public const MDR_DEBITO = 'MDR_DEBITO';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MDR_CREDITO,
            self::MDR_DEBITO
        ];
    }
}


