<?php
/**
 * InvestmentsFixedIncomeBankIndex
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Investments - Open Finance Brasil
 *
 * Estas APIs visam o compartilhamento de dados sobre Investimentos e suas características entre as Instituições Financeiras participantes do Open Finance Brasil
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InvestmentsFixedIncomeBankIndex Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UinvestmentsInvestmentsFixedIncomeBankIndex implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InvestmentsFixedIncomeBankIndex';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'indexer' => '\OpenAPI\Client\Model\EnumInvestmentsFixedIncomeBankIndexer',
        'indexer_additional_info' => 'string',
        'issue_remuneration_rate' => '\OpenAPI\Client\Model\InvestmentsNoIdentificationFrequencyDistribution'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'indexer' => null,
        'indexer_additional_info' => null,
        'issue_remuneration_rate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'indexer' => false,
        'indexer_additional_info' => false,
        'issue_remuneration_rate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'indexer' => 'indexer',
        'indexer_additional_info' => 'indexerAdditionalInfo',
        'issue_remuneration_rate' => 'issueRemunerationRate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'indexer' => 'setIndexer',
        'indexer_additional_info' => 'setIndexerAdditionalInfo',
        'issue_remuneration_rate' => 'setIssueRemunerationRate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'indexer' => 'getIndexer',
        'indexer_additional_info' => 'getIndexerAdditionalInfo',
        'issue_remuneration_rate' => 'getIssueRemunerationRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('indexer', $data ?? [], null);
        $this->setIfExists('indexer_additional_info', $data ?? [], null);
        $this->setIfExists('issue_remuneration_rate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['indexer'] === null) {
            $invalidProperties[] = "'indexer' can't be null";
        }
        if (!is_null($this->container['indexer_additional_info']) && (mb_strlen($this->container['indexer_additional_info']) > 140)) {
            $invalidProperties[] = "invalid value for 'indexer_additional_info', the character length must be smaller than or equal to 140.";
        }

        if (!is_null($this->container['indexer_additional_info']) && !preg_match("/[\\w\\W\\s]*/", $this->container['indexer_additional_info'])) {
            $invalidProperties[] = "invalid value for 'indexer_additional_info', must be conform to the pattern /[\\w\\W\\s]*/.";
        }

        if ($this->container['issue_remuneration_rate'] === null) {
            $invalidProperties[] = "'issue_remuneration_rate' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets indexer
     *
     * @return \OpenAPI\Client\Model\EnumInvestmentsFixedIncomeBankIndexer
     */
    public function getIndexer()
    {
        return $this->container['indexer'];
    }

    /**
     * Sets indexer
     *
     * @param \OpenAPI\Client\Model\EnumInvestmentsFixedIncomeBankIndexer $indexer indexer
     *
     * @return self
     */
    public function setIndexer($indexer)
    {
        if (is_null($indexer)) {
            throw new \InvalidArgumentException('non-nullable indexer cannot be null');
        }
        $this->container['indexer'] = $indexer;

        return $this;
    }

    /**
     * Gets indexer_additional_info
     *
     * @return string|null
     */
    public function getIndexerAdditionalInfo()
    {
        return $this->container['indexer_additional_info'];
    }

    /**
     * Sets indexer_additional_info
     *
     * @param string|null $indexer_additional_info Campo livre para preenchimento das informações adicionais referente ao encargo.  [Restrição] Obrigatório quando \"indexer\" for igual 'OUTROS'.
     *
     * @return self
     */
    public function setIndexerAdditionalInfo($indexer_additional_info)
    {
        if (is_null($indexer_additional_info)) {
            throw new \InvalidArgumentException('non-nullable indexer_additional_info cannot be null');
        }
        if ((mb_strlen($indexer_additional_info) > 140)) {
            throw new \InvalidArgumentException('invalid length for $indexer_additional_info when calling InvestmentsFixedIncomeBankIndex., must be smaller than or equal to 140.');
        }
        if ((!preg_match("/[\\w\\W\\s]*/", ObjectSerializer::toString($indexer_additional_info)))) {
            throw new \InvalidArgumentException("invalid value for \$indexer_additional_info when calling InvestmentsFixedIncomeBankIndex., must conform to the pattern /[\\w\\W\\s]*/.");
        }

        $this->container['indexer_additional_info'] = $indexer_additional_info;

        return $this;
    }

    /**
     * Gets issue_remuneration_rate
     *
     * @return \OpenAPI\Client\Model\InvestmentsNoIdentificationFrequencyDistribution
     */
    public function getIssueRemunerationRate()
    {
        return $this->container['issue_remuneration_rate'];
    }

    /**
     * Sets issue_remuneration_rate
     *
     * @param \OpenAPI\Client\Model\InvestmentsNoIdentificationFrequencyDistribution $issue_remuneration_rate issue_remuneration_rate
     *
     * @return self
     */
    public function setIssueRemunerationRate($issue_remuneration_rate)
    {
        if (is_null($issue_remuneration_rate)) {
            throw new \InvalidArgumentException('non-nullable issue_remuneration_rate cannot be null');
        }
        $this->container['issue_remuneration_rate'] = $issue_remuneration_rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


