<?php
/**
 * EnumExpirationGracePeriod
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Investments - Open Finance Brasil
 *
 * Estas APIs visam o compartilhamento de dados sobre Investimentos e suas características entre as Instituições Financeiras participantes do Open Finance Brasil
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EnumExpirationGracePeriod Class Doc Comment
 *
 * @category Class
 * @description Faixa de valores para prazos de vencimento e carência.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UinvestmentsEnumExpirationGracePeriod
{
    /**
     * Possible values of this enum
     */
    public const _1_360 = '1_360';

    public const _361_1080 = '361_1080';

    public const _1081 = '1081+';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_1_360,
            self::_361_1080,
            self::_1081
        ];
    }
}


