<?php
/**
 * ServiceBundleServiceDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API OpenData Accounts do Open Finance Brasil
 *
 * A API descrita neste documento é referente as API Accounts da fase OpenData do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceBundleServiceDetail Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Uopendata-accountsServiceBundleServiceDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServiceBundleServiceDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'charging_trigger_info' => 'string',
        'event_limit_quantity' => 'string',
        'free_event_quantity' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'charging_trigger_info' => null,
        'event_limit_quantity' => null,
        'free_event_quantity' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'code' => false,
        'charging_trigger_info' => false,
        'event_limit_quantity' => false,
        'free_event_quantity' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'charging_trigger_info' => 'chargingTriggerInfo',
        'event_limit_quantity' => 'eventLimitQuantity',
        'free_event_quantity' => 'freeEventQuantity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'charging_trigger_info' => 'setChargingTriggerInfo',
        'event_limit_quantity' => 'setEventLimitQuantity',
        'free_event_quantity' => 'setFreeEventQuantity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'charging_trigger_info' => 'getChargingTriggerInfo',
        'event_limit_quantity' => 'getEventLimitQuantity',
        'free_event_quantity' => 'getFreeEventQuantity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('charging_trigger_info', $data ?? [], null);
        $this->setIfExists('event_limit_quantity', $data ?? [], null);
        $this->setIfExists('free_event_quantity', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ((mb_strlen($this->container['code']) > 100)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 100.";
        }

        if (!preg_match("/^(?!\\s)[\\w\\W\\s]*[^\\s]$/", $this->container['code'])) {
            $invalidProperties[] = "invalid value for 'code', must be conform to the pattern /^(?!\\s)[\\w\\W\\s]*[^\\s]$/.";
        }

        if ($this->container['charging_trigger_info'] === null) {
            $invalidProperties[] = "'charging_trigger_info' can't be null";
        }
        if ((mb_strlen($this->container['charging_trigger_info']) > 2000)) {
            $invalidProperties[] = "invalid value for 'charging_trigger_info', the character length must be smaller than or equal to 2000.";
        }

        if (!preg_match("/^(?!\\s)[\\w\\W\\s]*[^\\s]$/", $this->container['charging_trigger_info'])) {
            $invalidProperties[] = "invalid value for 'charging_trigger_info', must be conform to the pattern /^(?!\\s)[\\w\\W\\s]*[^\\s]$/.";
        }

        if ($this->container['event_limit_quantity'] === null) {
            $invalidProperties[] = "'event_limit_quantity' can't be null";
        }
        if ((mb_strlen($this->container['event_limit_quantity']) > 6)) {
            $invalidProperties[] = "invalid value for 'event_limit_quantity', the character length must be smaller than or equal to 6.";
        }

        if ((mb_strlen($this->container['event_limit_quantity']) < 1)) {
            $invalidProperties[] = "invalid value for 'event_limit_quantity', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^(\\d{1,6}){1}$/", $this->container['event_limit_quantity'])) {
            $invalidProperties[] = "invalid value for 'event_limit_quantity', must be conform to the pattern /^(\\d{1,6}){1}$/.";
        }

        if ($this->container['free_event_quantity'] === null) {
            $invalidProperties[] = "'free_event_quantity' can't be null";
        }
        if ((mb_strlen($this->container['free_event_quantity']) > 6)) {
            $invalidProperties[] = "invalid value for 'free_event_quantity', the character length must be smaller than or equal to 6.";
        }

        if ((mb_strlen($this->container['free_event_quantity']) < 1)) {
            $invalidProperties[] = "invalid value for 'free_event_quantity', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^(\\d{1,6}){1}$/", $this->container['free_event_quantity'])) {
            $invalidProperties[] = "invalid value for 'free_event_quantity', must be conform to the pattern /^(\\d{1,6}){1}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code Código que identifica o Serviço que compõe o Pacote de Serviços, podendo ser da lista de Serviços Prioritários ou Outros Serviços. p.ex. segundo Resolução 3.919 do Bacen: 'SAQUE_TERMINAL'.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        if ((mb_strlen($code) > 100)) {
            throw new \InvalidArgumentException('invalid length for $code when calling ServiceBundleServiceDetail., must be smaller than or equal to 100.');
        }
        if ((!preg_match("/^(?!\\s)[\\w\\W\\s]*[^\\s]$/", ObjectSerializer::toString($code)))) {
            throw new \InvalidArgumentException("invalid value for \$code when calling ServiceBundleServiceDetail., must conform to the pattern /^(?!\\s)[\\w\\W\\s]*[^\\s]$/.");
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets charging_trigger_info
     *
     * @return string
     */
    public function getChargingTriggerInfo()
    {
        return $this->container['charging_trigger_info'];
    }

    /**
     * Sets charging_trigger_info
     *
     * @param string $charging_trigger_info Fatos geradores de cobrança que incidem sobre serviço que compõe o Pacote de Serviços.
     *
     * @return self
     */
    public function setChargingTriggerInfo($charging_trigger_info)
    {
        if (is_null($charging_trigger_info)) {
            throw new \InvalidArgumentException('non-nullable charging_trigger_info cannot be null');
        }
        if ((mb_strlen($charging_trigger_info) > 2000)) {
            throw new \InvalidArgumentException('invalid length for $charging_trigger_info when calling ServiceBundleServiceDetail., must be smaller than or equal to 2000.');
        }
        if ((!preg_match("/^(?!\\s)[\\w\\W\\s]*[^\\s]$/", ObjectSerializer::toString($charging_trigger_info)))) {
            throw new \InvalidArgumentException("invalid value for \$charging_trigger_info when calling ServiceBundleServiceDetail., must conform to the pattern /^(?!\\s)[\\w\\W\\s]*[^\\s]$/.");
        }

        $this->container['charging_trigger_info'] = $charging_trigger_info;

        return $this;
    }

    /**
     * Gets event_limit_quantity
     *
     * @return string
     */
    public function getEventLimitQuantity()
    {
        return $this->container['event_limit_quantity'];
    }

    /**
     * Sets event_limit_quantity
     *
     * @param string $event_limit_quantity Segundo Resolução  4196, BCB, de 2013: Quantidade de eventos previstos no Pacote de Serviços (Número de eventos incluídos no mês) p.ex.'2'. No caso de quantidade ilimitada, reportar 999999
     *
     * @return self
     */
    public function setEventLimitQuantity($event_limit_quantity)
    {
        if (is_null($event_limit_quantity)) {
            throw new \InvalidArgumentException('non-nullable event_limit_quantity cannot be null');
        }
        if ((mb_strlen($event_limit_quantity) > 6)) {
            throw new \InvalidArgumentException('invalid length for $event_limit_quantity when calling ServiceBundleServiceDetail., must be smaller than or equal to 6.');
        }
        if ((mb_strlen($event_limit_quantity) < 1)) {
            throw new \InvalidArgumentException('invalid length for $event_limit_quantity when calling ServiceBundleServiceDetail., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^(\\d{1,6}){1}$/", ObjectSerializer::toString($event_limit_quantity)))) {
            throw new \InvalidArgumentException("invalid value for \$event_limit_quantity when calling ServiceBundleServiceDetail., must conform to the pattern /^(\\d{1,6}){1}$/.");
        }

        $this->container['event_limit_quantity'] = $event_limit_quantity;

        return $this;
    }

    /**
     * Gets free_event_quantity
     *
     * @return string
     */
    public function getFreeEventQuantity()
    {
        return $this->container['free_event_quantity'];
    }

    /**
     * Sets free_event_quantity
     *
     * @param string $free_event_quantity Segundo Resolução  4196, BCB, de 2013: Quantidade de eventos previstos no Pacote de Serviços com isenção de Tarifa.p.ex.'1'  No caso de quantidade ilimitada, reportar 999999
     *
     * @return self
     */
    public function setFreeEventQuantity($free_event_quantity)
    {
        if (is_null($free_event_quantity)) {
            throw new \InvalidArgumentException('non-nullable free_event_quantity cannot be null');
        }
        if ((mb_strlen($free_event_quantity) > 6)) {
            throw new \InvalidArgumentException('invalid length for $free_event_quantity when calling ServiceBundleServiceDetail., must be smaller than or equal to 6.');
        }
        if ((mb_strlen($free_event_quantity) < 1)) {
            throw new \InvalidArgumentException('invalid length for $free_event_quantity when calling ServiceBundleServiceDetail., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^(\\d{1,6}){1}$/", ObjectSerializer::toString($free_event_quantity)))) {
            throw new \InvalidArgumentException("invalid value for \$free_event_quantity when calling ServiceBundleServiceDetail., must conform to the pattern /^(\\d{1,6}){1}$/.");
        }

        $this->container['free_event_quantity'] = $free_event_quantity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


