<?php
/**
 * CreditCardInterest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API OpenData Credit Cards do Open Finance Brasil
 *
 * A API descrita neste documento é referente as API Credit Cards da fase OpenData do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CreditCardInterest Class Doc Comment
 *
 * @category Class
 * @description Informações sobre taxas de juros
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Uopendata-creditcardsCreditCardInterest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreditCardInterest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rates' => '\OpenAPI\Client\Model\InterestRate[]',
        'instalment_rates' => '\OpenAPI\Client\Model\InterestRate[]',
        'other_credits' => '\OpenAPI\Client\Model\CreditCardInterestRate[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rates' => null,
        'instalment_rates' => null,
        'other_credits' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rates' => false,
        'instalment_rates' => false,
        'other_credits' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rates' => 'rates',
        'instalment_rates' => 'instalmentRates',
        'other_credits' => 'otherCredits'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rates' => 'setRates',
        'instalment_rates' => 'setInstalmentRates',
        'other_credits' => 'setOtherCredits'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rates' => 'getRates',
        'instalment_rates' => 'getInstalmentRates',
        'other_credits' => 'getOtherCredits'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rates', $data ?? [], null);
        $this->setIfExists('instalment_rates', $data ?? [], null);
        $this->setIfExists('other_credits', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rates'] === null) {
            $invalidProperties[] = "'rates' can't be null";
        }
        if ((count($this->container['rates']) > 20)) {
            $invalidProperties[] = "invalid value for 'rates', number of items must be less than or equal to 20.";
        }

        if ((count($this->container['rates']) < 1)) {
            $invalidProperties[] = "invalid value for 'rates', number of items must be greater than or equal to 1.";
        }

        if ($this->container['instalment_rates'] === null) {
            $invalidProperties[] = "'instalment_rates' can't be null";
        }
        if ((count($this->container['instalment_rates']) > 20)) {
            $invalidProperties[] = "invalid value for 'instalment_rates', number of items must be less than or equal to 20.";
        }

        if ((count($this->container['instalment_rates']) < 1)) {
            $invalidProperties[] = "invalid value for 'instalment_rates', number of items must be greater than or equal to 1.";
        }

        if ($this->container['other_credits'] === null) {
            $invalidProperties[] = "'other_credits' can't be null";
        }
        if ((count($this->container['other_credits']) > 3)) {
            $invalidProperties[] = "invalid value for 'other_credits', number of items must be less than or equal to 3.";
        }

        if ((count($this->container['other_credits']) < 1)) {
            $invalidProperties[] = "invalid value for 'other_credits', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rates
     *
     * @return \OpenAPI\Client\Model\InterestRate[]
     */
    public function getRates()
    {
        return $this->container['rates'];
    }

    /**
     * Sets rates
     *
     * @param \OpenAPI\Client\Model\InterestRate[] $rates Lista da representação que traz o conjunto de informações necessárias para demonstrar a distribuição de frequências das taxas de juros remuneratórios para crédito rotativo
     *
     * @return self
     */
    public function setRates($rates)
    {
        if (is_null($rates)) {
            throw new \InvalidArgumentException('non-nullable rates cannot be null');
        }

        if ((count($rates) > 20)) {
            throw new \InvalidArgumentException('invalid value for $rates when calling CreditCardInterest., number of items must be less than or equal to 20.');
        }
        if ((count($rates) < 1)) {
            throw new \InvalidArgumentException('invalid length for $rates when calling CreditCardInterest., number of items must be greater than or equal to 1.');
        }
        $this->container['rates'] = $rates;

        return $this;
    }

    /**
     * Gets instalment_rates
     *
     * @return \OpenAPI\Client\Model\InterestRate[]
     */
    public function getInstalmentRates()
    {
        return $this->container['instalment_rates'];
    }

    /**
     * Sets instalment_rates
     *
     * @param \OpenAPI\Client\Model\InterestRate[] $instalment_rates Lista da representação que traz o conjunto de informações necessárias para demonstrar a distribuição de frequências das taxas de juros remuneratórios para parcelamento do saldo devedor
     *
     * @return self
     */
    public function setInstalmentRates($instalment_rates)
    {
        if (is_null($instalment_rates)) {
            throw new \InvalidArgumentException('non-nullable instalment_rates cannot be null');
        }

        if ((count($instalment_rates) > 20)) {
            throw new \InvalidArgumentException('invalid value for $instalment_rates when calling CreditCardInterest., number of items must be less than or equal to 20.');
        }
        if ((count($instalment_rates) < 1)) {
            throw new \InvalidArgumentException('invalid length for $instalment_rates when calling CreditCardInterest., number of items must be greater than or equal to 1.');
        }
        $this->container['instalment_rates'] = $instalment_rates;

        return $this;
    }

    /**
     * Gets other_credits
     *
     * @return \OpenAPI\Client\Model\CreditCardInterestRate[]
     */
    public function getOtherCredits()
    {
        return $this->container['other_credits'];
    }

    /**
     * Sets other_credits
     *
     * @param \OpenAPI\Client\Model\CreditCardInterestRate[] $other_credits Lista de outras operações de crédito
     *
     * @return self
     */
    public function setOtherCredits($other_credits)
    {
        if (is_null($other_credits)) {
            throw new \InvalidArgumentException('non-nullable other_credits cannot be null');
        }

        if ((count($other_credits) > 3)) {
            throw new \InvalidArgumentException('invalid value for $other_credits when calling CreditCardInterest., number of items must be less than or equal to 3.');
        }
        if ((count($other_credits) < 1)) {
            throw new \InvalidArgumentException('invalid length for $other_credits when calling CreditCardInterest., number of items must be greater than or equal to 1.');
        }
        $this->container['other_credits'] = $other_credits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


