<?php
/**
 * AccountType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API OpenData Accounts do Open Finance Brasil
 *
 * A API descrita neste documento é referente as API Accounts da fase OpenData do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AccountType Class Doc Comment
 *
 * @category Class
 * @description Tipos de contas ofertadas para pessoa natural ou jurídica, p.ex. &#39;CONTA_DEPOSITO_A_VISTA&#39;. Conta de depósito à vista ou Conta corrente - é o tipo mais comum. Nela, o dinheiro fica à sua disposição para ser sacado a qualquer momento. Essa conta não gera rendimentos para o depositante Conta poupança - foi criada para estimular as pessoas a pouparem. O dinheiro que ficar na conta por trinta dias passa a gerar rendimentos, com isenção de imposto de renda para quem declara. Ou seja, o dinheiro “cresce” (rende) enquanto ficar guardado na conta. Cada depósito terá rendimentos de mês em mês, sempre no dia do mês em que o dinheiro tiver sido depositado Conta de pagamento pré-paga: segundo CIRCULAR Nº 3.680, BCB de  2013, é a &#39;destinada à execução de transações de pagamento em moeda eletrônica realizadas com base em fundos denominados em reais previamente aportados&#39;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Uopendata-accountsAccountType
{
    /**
     * Possible values of this enum
     */
    public const CONTA_DEPOSITO_A_VISTA = 'CONTA_DEPOSITO_A_VISTA';

    public const CONTA_POUPANCA = 'CONTA_POUPANCA';

    public const CONTA_PAGAMENTO_PRE_PAGA = 'CONTA_PAGAMENTO_PRE_PAGA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONTA_DEPOSITO_A_VISTA,
            self::CONTA_POUPANCA,
            self::CONTA_PAGAMENTO_PRE_PAGA
        ];
    }
}


