<?php
/**
 * ClientCreationResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Participantes Open Finance Brasil
 *
 * Informações sobre os participantes do Open Finance Brasil que estão registrados no Diretório.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ClientCreationResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UparticipantsClientCreationResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ClientCreationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'application_type' => 'string',
        'tls_client_auth_subject_dn' => 'string',
        'grant_types' => 'string[]',
        'id_token_signed_response_alg' => 'string',
        'require_auth_time' => 'bool',
        'subject_type' => 'string',
        'response_types' => 'string[]',
        'post_logout_redirect_uris' => 'string[]',
        'token_endpoint_auth_method' => 'string',
        'introspection_endpoint_auth_method' => 'string',
        'revocation_endpoint_auth_method' => 'string',
        'client_id_issued_at' => 'float',
        'client_id' => 'string',
        'jwks_uri' => 'string',
        'registration_client_uri' => 'string',
        'registration_access_token' => 'string',
        'redirect_uris' => 'string[]',
        'request_uris' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'application_type' => null,
        'tls_client_auth_subject_dn' => null,
        'grant_types' => null,
        'id_token_signed_response_alg' => null,
        'require_auth_time' => null,
        'subject_type' => null,
        'response_types' => null,
        'post_logout_redirect_uris' => null,
        'token_endpoint_auth_method' => null,
        'introspection_endpoint_auth_method' => null,
        'revocation_endpoint_auth_method' => null,
        'client_id_issued_at' => null,
        'client_id' => null,
        'jwks_uri' => null,
        'registration_client_uri' => null,
        'registration_access_token' => null,
        'redirect_uris' => null,
        'request_uris' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'application_type' => false,
        'tls_client_auth_subject_dn' => false,
        'grant_types' => false,
        'id_token_signed_response_alg' => false,
        'require_auth_time' => false,
        'subject_type' => false,
        'response_types' => false,
        'post_logout_redirect_uris' => false,
        'token_endpoint_auth_method' => false,
        'introspection_endpoint_auth_method' => false,
        'revocation_endpoint_auth_method' => false,
        'client_id_issued_at' => false,
        'client_id' => false,
        'jwks_uri' => false,
        'registration_client_uri' => false,
        'registration_access_token' => false,
        'redirect_uris' => false,
        'request_uris' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'application_type' => 'application_type',
        'tls_client_auth_subject_dn' => 'tls_client_auth_subject_dn',
        'grant_types' => 'grant_types',
        'id_token_signed_response_alg' => 'id_token_signed_response_alg',
        'require_auth_time' => 'require_auth_time',
        'subject_type' => 'subject_type',
        'response_types' => 'response_types',
        'post_logout_redirect_uris' => 'post_logout_redirect_uris',
        'token_endpoint_auth_method' => 'token_endpoint_auth_method',
        'introspection_endpoint_auth_method' => 'introspection_endpoint_auth_method',
        'revocation_endpoint_auth_method' => 'revocation_endpoint_auth_method',
        'client_id_issued_at' => 'client_id_issued_at',
        'client_id' => 'client_id',
        'jwks_uri' => 'jwks_uri',
        'registration_client_uri' => 'registration_client_uri',
        'registration_access_token' => 'registration_access_token',
        'redirect_uris' => 'redirect_uris',
        'request_uris' => 'request_uris'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'application_type' => 'setApplicationType',
        'tls_client_auth_subject_dn' => 'setTlsClientAuthSubjectDn',
        'grant_types' => 'setGrantTypes',
        'id_token_signed_response_alg' => 'setIdTokenSignedResponseAlg',
        'require_auth_time' => 'setRequireAuthTime',
        'subject_type' => 'setSubjectType',
        'response_types' => 'setResponseTypes',
        'post_logout_redirect_uris' => 'setPostLogoutRedirectUris',
        'token_endpoint_auth_method' => 'setTokenEndpointAuthMethod',
        'introspection_endpoint_auth_method' => 'setIntrospectionEndpointAuthMethod',
        'revocation_endpoint_auth_method' => 'setRevocationEndpointAuthMethod',
        'client_id_issued_at' => 'setClientIdIssuedAt',
        'client_id' => 'setClientId',
        'jwks_uri' => 'setJwksUri',
        'registration_client_uri' => 'setRegistrationClientUri',
        'registration_access_token' => 'setRegistrationAccessToken',
        'redirect_uris' => 'setRedirectUris',
        'request_uris' => 'setRequestUris'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'application_type' => 'getApplicationType',
        'tls_client_auth_subject_dn' => 'getTlsClientAuthSubjectDn',
        'grant_types' => 'getGrantTypes',
        'id_token_signed_response_alg' => 'getIdTokenSignedResponseAlg',
        'require_auth_time' => 'getRequireAuthTime',
        'subject_type' => 'getSubjectType',
        'response_types' => 'getResponseTypes',
        'post_logout_redirect_uris' => 'getPostLogoutRedirectUris',
        'token_endpoint_auth_method' => 'getTokenEndpointAuthMethod',
        'introspection_endpoint_auth_method' => 'getIntrospectionEndpointAuthMethod',
        'revocation_endpoint_auth_method' => 'getRevocationEndpointAuthMethod',
        'client_id_issued_at' => 'getClientIdIssuedAt',
        'client_id' => 'getClientId',
        'jwks_uri' => 'getJwksUri',
        'registration_client_uri' => 'getRegistrationClientUri',
        'registration_access_token' => 'getRegistrationAccessToken',
        'redirect_uris' => 'getRedirectUris',
        'request_uris' => 'getRequestUris'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const APPLICATION_TYPE_WEB = 'web';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplicationTypeAllowableValues()
    {
        return [
            self::APPLICATION_TYPE_WEB,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('application_type', $data ?? [], 'web');
        $this->setIfExists('tls_client_auth_subject_dn', $data ?? [], null);
        $this->setIfExists('grant_types', $data ?? [], null);
        $this->setIfExists('id_token_signed_response_alg', $data ?? [], null);
        $this->setIfExists('require_auth_time', $data ?? [], null);
        $this->setIfExists('subject_type', $data ?? [], null);
        $this->setIfExists('response_types', $data ?? [], null);
        $this->setIfExists('post_logout_redirect_uris', $data ?? [], null);
        $this->setIfExists('token_endpoint_auth_method', $data ?? [], null);
        $this->setIfExists('introspection_endpoint_auth_method', $data ?? [], null);
        $this->setIfExists('revocation_endpoint_auth_method', $data ?? [], null);
        $this->setIfExists('client_id_issued_at', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('jwks_uri', $data ?? [], null);
        $this->setIfExists('registration_client_uri', $data ?? [], null);
        $this->setIfExists('registration_access_token', $data ?? [], null);
        $this->setIfExists('redirect_uris', $data ?? [], null);
        $this->setIfExists('request_uris', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getApplicationTypeAllowableValues();
        if (!is_null($this->container['application_type']) && !in_array($this->container['application_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'application_type', must be one of '%s'",
                $this->container['application_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets application_type
     *
     * @return string|null
     */
    public function getApplicationType()
    {
        return $this->container['application_type'];
    }

    /**
     * Sets application_type
     *
     * @param string|null $application_type OIDC application type response
     *
     * @return self
     */
    public function setApplicationType($application_type)
    {
        if (is_null($application_type)) {
            throw new \InvalidArgumentException('non-nullable application_type cannot be null');
        }
        $allowedValues = $this->getApplicationTypeAllowableValues();
        if (!in_array($application_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'application_type', must be one of '%s'",
                    $application_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['application_type'] = $application_type;

        return $this;
    }

    /**
     * Gets tls_client_auth_subject_dn
     *
     * @return string|null
     */
    public function getTlsClientAuthSubjectDn()
    {
        return $this->container['tls_client_auth_subject_dn'];
    }

    /**
     * Sets tls_client_auth_subject_dn
     *
     * @param string|null $tls_client_auth_subject_dn the subject dn used to authenticate this client
     *
     * @return self
     */
    public function setTlsClientAuthSubjectDn($tls_client_auth_subject_dn)
    {
        if (is_null($tls_client_auth_subject_dn)) {
            throw new \InvalidArgumentException('non-nullable tls_client_auth_subject_dn cannot be null');
        }
        $this->container['tls_client_auth_subject_dn'] = $tls_client_auth_subject_dn;

        return $this;
    }

    /**
     * Gets grant_types
     *
     * @return string[]|null
     */
    public function getGrantTypes()
    {
        return $this->container['grant_types'];
    }

    /**
     * Sets grant_types
     *
     * @param string[]|null $grant_types grant_types
     *
     * @return self
     */
    public function setGrantTypes($grant_types)
    {
        if (is_null($grant_types)) {
            throw new \InvalidArgumentException('non-nullable grant_types cannot be null');
        }
        $this->container['grant_types'] = $grant_types;

        return $this;
    }

    /**
     * Gets id_token_signed_response_alg
     *
     * @return string|null
     */
    public function getIdTokenSignedResponseAlg()
    {
        return $this->container['id_token_signed_response_alg'];
    }

    /**
     * Sets id_token_signed_response_alg
     *
     * @param string|null $id_token_signed_response_alg id_token_signed_response_alg
     *
     * @return self
     */
    public function setIdTokenSignedResponseAlg($id_token_signed_response_alg)
    {
        if (is_null($id_token_signed_response_alg)) {
            throw new \InvalidArgumentException('non-nullable id_token_signed_response_alg cannot be null');
        }
        $this->container['id_token_signed_response_alg'] = $id_token_signed_response_alg;

        return $this;
    }

    /**
     * Gets require_auth_time
     *
     * @return bool|null
     */
    public function getRequireAuthTime()
    {
        return $this->container['require_auth_time'];
    }

    /**
     * Sets require_auth_time
     *
     * @param bool|null $require_auth_time require_auth_time
     *
     * @return self
     */
    public function setRequireAuthTime($require_auth_time)
    {
        if (is_null($require_auth_time)) {
            throw new \InvalidArgumentException('non-nullable require_auth_time cannot be null');
        }
        $this->container['require_auth_time'] = $require_auth_time;

        return $this;
    }

    /**
     * Gets subject_type
     *
     * @return string|null
     */
    public function getSubjectType()
    {
        return $this->container['subject_type'];
    }

    /**
     * Sets subject_type
     *
     * @param string|null $subject_type subject_type
     *
     * @return self
     */
    public function setSubjectType($subject_type)
    {
        if (is_null($subject_type)) {
            throw new \InvalidArgumentException('non-nullable subject_type cannot be null');
        }
        $this->container['subject_type'] = $subject_type;

        return $this;
    }

    /**
     * Gets response_types
     *
     * @return string[]|null
     */
    public function getResponseTypes()
    {
        return $this->container['response_types'];
    }

    /**
     * Sets response_types
     *
     * @param string[]|null $response_types response_types
     *
     * @return self
     */
    public function setResponseTypes($response_types)
    {
        if (is_null($response_types)) {
            throw new \InvalidArgumentException('non-nullable response_types cannot be null');
        }
        $this->container['response_types'] = $response_types;

        return $this;
    }

    /**
     * Gets post_logout_redirect_uris
     *
     * @return string[]|null
     */
    public function getPostLogoutRedirectUris()
    {
        return $this->container['post_logout_redirect_uris'];
    }

    /**
     * Sets post_logout_redirect_uris
     *
     * @param string[]|null $post_logout_redirect_uris post_logout_redirect_uris
     *
     * @return self
     */
    public function setPostLogoutRedirectUris($post_logout_redirect_uris)
    {
        if (is_null($post_logout_redirect_uris)) {
            throw new \InvalidArgumentException('non-nullable post_logout_redirect_uris cannot be null');
        }
        $this->container['post_logout_redirect_uris'] = $post_logout_redirect_uris;

        return $this;
    }

    /**
     * Gets token_endpoint_auth_method
     *
     * @return string|null
     */
    public function getTokenEndpointAuthMethod()
    {
        return $this->container['token_endpoint_auth_method'];
    }

    /**
     * Sets token_endpoint_auth_method
     *
     * @param string|null $token_endpoint_auth_method token_endpoint_auth_method
     *
     * @return self
     */
    public function setTokenEndpointAuthMethod($token_endpoint_auth_method)
    {
        if (is_null($token_endpoint_auth_method)) {
            throw new \InvalidArgumentException('non-nullable token_endpoint_auth_method cannot be null');
        }
        $this->container['token_endpoint_auth_method'] = $token_endpoint_auth_method;

        return $this;
    }

    /**
     * Gets introspection_endpoint_auth_method
     *
     * @return string|null
     */
    public function getIntrospectionEndpointAuthMethod()
    {
        return $this->container['introspection_endpoint_auth_method'];
    }

    /**
     * Sets introspection_endpoint_auth_method
     *
     * @param string|null $introspection_endpoint_auth_method introspection_endpoint_auth_method
     *
     * @return self
     */
    public function setIntrospectionEndpointAuthMethod($introspection_endpoint_auth_method)
    {
        if (is_null($introspection_endpoint_auth_method)) {
            throw new \InvalidArgumentException('non-nullable introspection_endpoint_auth_method cannot be null');
        }
        $this->container['introspection_endpoint_auth_method'] = $introspection_endpoint_auth_method;

        return $this;
    }

    /**
     * Gets revocation_endpoint_auth_method
     *
     * @return string|null
     */
    public function getRevocationEndpointAuthMethod()
    {
        return $this->container['revocation_endpoint_auth_method'];
    }

    /**
     * Sets revocation_endpoint_auth_method
     *
     * @param string|null $revocation_endpoint_auth_method revocation_endpoint_auth_method
     *
     * @return self
     */
    public function setRevocationEndpointAuthMethod($revocation_endpoint_auth_method)
    {
        if (is_null($revocation_endpoint_auth_method)) {
            throw new \InvalidArgumentException('non-nullable revocation_endpoint_auth_method cannot be null');
        }
        $this->container['revocation_endpoint_auth_method'] = $revocation_endpoint_auth_method;

        return $this;
    }

    /**
     * Gets client_id_issued_at
     *
     * @return float|null
     */
    public function getClientIdIssuedAt()
    {
        return $this->container['client_id_issued_at'];
    }

    /**
     * Sets client_id_issued_at
     *
     * @param float|null $client_id_issued_at client_id_issued_at
     *
     * @return self
     */
    public function setClientIdIssuedAt($client_id_issued_at)
    {
        if (is_null($client_id_issued_at)) {
            throw new \InvalidArgumentException('non-nullable client_id_issued_at cannot be null');
        }
        $this->container['client_id_issued_at'] = $client_id_issued_at;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id client_id
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        if (is_null($client_id)) {
            throw new \InvalidArgumentException('non-nullable client_id cannot be null');
        }
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets jwks_uri
     *
     * @return string|null
     */
    public function getJwksUri()
    {
        return $this->container['jwks_uri'];
    }

    /**
     * Sets jwks_uri
     *
     * @param string|null $jwks_uri jwks_uri
     *
     * @return self
     */
    public function setJwksUri($jwks_uri)
    {
        if (is_null($jwks_uri)) {
            throw new \InvalidArgumentException('non-nullable jwks_uri cannot be null');
        }
        $this->container['jwks_uri'] = $jwks_uri;

        return $this;
    }

    /**
     * Gets registration_client_uri
     *
     * @return string|null
     */
    public function getRegistrationClientUri()
    {
        return $this->container['registration_client_uri'];
    }

    /**
     * Sets registration_client_uri
     *
     * @param string|null $registration_client_uri management uri location to manage client post creation
     *
     * @return self
     */
    public function setRegistrationClientUri($registration_client_uri)
    {
        if (is_null($registration_client_uri)) {
            throw new \InvalidArgumentException('non-nullable registration_client_uri cannot be null');
        }
        $this->container['registration_client_uri'] = $registration_client_uri;

        return $this;
    }

    /**
     * Gets registration_access_token
     *
     * @return string|null
     */
    public function getRegistrationAccessToken()
    {
        return $this->container['registration_access_token'];
    }

    /**
     * Sets registration_access_token
     *
     * @param string|null $registration_access_token token used to manage client post creation
     *
     * @return self
     */
    public function setRegistrationAccessToken($registration_access_token)
    {
        if (is_null($registration_access_token)) {
            throw new \InvalidArgumentException('non-nullable registration_access_token cannot be null');
        }
        $this->container['registration_access_token'] = $registration_access_token;

        return $this;
    }

    /**
     * Gets redirect_uris
     *
     * @return string[]|null
     */
    public function getRedirectUris()
    {
        return $this->container['redirect_uris'];
    }

    /**
     * Sets redirect_uris
     *
     * @param string[]|null $redirect_uris redirect_uris
     *
     * @return self
     */
    public function setRedirectUris($redirect_uris)
    {
        if (is_null($redirect_uris)) {
            throw new \InvalidArgumentException('non-nullable redirect_uris cannot be null');
        }
        $this->container['redirect_uris'] = $redirect_uris;

        return $this;
    }

    /**
     * Gets request_uris
     *
     * @return string[]|null
     */
    public function getRequestUris()
    {
        return $this->container['request_uris'];
    }

    /**
     * Sets request_uris
     *
     * @param string[]|null $request_uris request_uris
     *
     * @return self
     */
    public function setRequestUris($request_uris)
    {
        if (is_null($request_uris)) {
            throw new \InvalidArgumentException('non-nullable request_uris cannot be null');
        }
        $this->container['request_uris'] = $request_uris;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


