<?php
/**
 * OrganisationEnrol
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Participantes Open Finance Brasil
 *
 * Informações sobre os participantes do Open Finance Brasil que estão registrados no Diretório.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OrganisationEnrol Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrganisationEnrol implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrganisationEnrol';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'redirect_uris' => 'string[]',
        'token_endpoint_auth_method' => 'string',
        'grant_types' => 'string[]',
        'response_types' => 'string[]',
        'client_name' => 'mixed',
        'client_uri' => 'string',
        'logo_uri' => 'string',
        'scope' => 'string',
        'tos_uri' => 'string',
        'policy_uri' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'redirect_uris' => 'uri',
        'token_endpoint_auth_method' => null,
        'grant_types' => null,
        'response_types' => null,
        'client_name' => null,
        'client_uri' => 'uri',
        'logo_uri' => 'uri',
        'scope' => null,
        'tos_uri' => 'uri',
        'policy_uri' => 'uri'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'redirect_uris' => false,
        'token_endpoint_auth_method' => false,
        'grant_types' => false,
        'response_types' => false,
        'client_name' => true,
        'client_uri' => false,
        'logo_uri' => false,
        'scope' => false,
        'tos_uri' => false,
        'policy_uri' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'redirect_uris' => 'RedirectUris',
        'token_endpoint_auth_method' => 'TokenEndpointAuthMethod',
        'grant_types' => 'GrantTypes',
        'response_types' => 'ResponseTypes',
        'client_name' => 'ClientName',
        'client_uri' => 'ClientUri',
        'logo_uri' => 'LogoUri',
        'scope' => 'Scope',
        'tos_uri' => 'TosUri',
        'policy_uri' => 'PolicyUri'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'redirect_uris' => 'setRedirectUris',
        'token_endpoint_auth_method' => 'setTokenEndpointAuthMethod',
        'grant_types' => 'setGrantTypes',
        'response_types' => 'setResponseTypes',
        'client_name' => 'setClientName',
        'client_uri' => 'setClientUri',
        'logo_uri' => 'setLogoUri',
        'scope' => 'setScope',
        'tos_uri' => 'setTosUri',
        'policy_uri' => 'setPolicyUri'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'redirect_uris' => 'getRedirectUris',
        'token_endpoint_auth_method' => 'getTokenEndpointAuthMethod',
        'grant_types' => 'getGrantTypes',
        'response_types' => 'getResponseTypes',
        'client_name' => 'getClientName',
        'client_uri' => 'getClientUri',
        'logo_uri' => 'getLogoUri',
        'scope' => 'getScope',
        'tos_uri' => 'getTosUri',
        'policy_uri' => 'getPolicyUri'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('redirect_uris', $data ?? [], null);
        $this->setIfExists('token_endpoint_auth_method', $data ?? [], null);
        $this->setIfExists('grant_types', $data ?? [], null);
        $this->setIfExists('response_types', $data ?? [], null);
        $this->setIfExists('client_name', $data ?? [], null);
        $this->setIfExists('client_uri', $data ?? [], null);
        $this->setIfExists('logo_uri', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('tos_uri', $data ?? [], null);
        $this->setIfExists('policy_uri', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['redirect_uris'] === null) {
            $invalidProperties[] = "'redirect_uris' can't be null";
        }
        if ($this->container['token_endpoint_auth_method'] === null) {
            $invalidProperties[] = "'token_endpoint_auth_method' can't be null";
        }
        if ((mb_strlen($this->container['token_endpoint_auth_method']) > 256)) {
            $invalidProperties[] = "invalid value for 'token_endpoint_auth_method', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['token_endpoint_auth_method']) < 1)) {
            $invalidProperties[] = "invalid value for 'token_endpoint_auth_method', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['grant_types'] === null) {
            $invalidProperties[] = "'grant_types' can't be null";
        }
        if ($this->container['response_types'] === null) {
            $invalidProperties[] = "'response_types' can't be null";
        }
        if ($this->container['client_name'] === null) {
            $invalidProperties[] = "'client_name' can't be null";
        }
        if ((mb_strlen($this->container['client_name']) > 256)) {
            $invalidProperties[] = "invalid value for 'client_name', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['client_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'client_name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['client_uri'] === null) {
            $invalidProperties[] = "'client_uri' can't be null";
        }
        if ((mb_strlen($this->container['client_uri']) > 256)) {
            $invalidProperties[] = "invalid value for 'client_uri', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/^(http:\/\/|https:\/\/).*/", $this->container['client_uri'])) {
            $invalidProperties[] = "invalid value for 'client_uri', must be conform to the pattern /^(http:\/\/|https:\/\/).*/.";
        }

        if ($this->container['logo_uri'] === null) {
            $invalidProperties[] = "'logo_uri' can't be null";
        }
        if ((mb_strlen($this->container['logo_uri']) > 256)) {
            $invalidProperties[] = "invalid value for 'logo_uri', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/^(http:\/\/|https:\/\/).*/", $this->container['logo_uri'])) {
            $invalidProperties[] = "invalid value for 'logo_uri', must be conform to the pattern /^(http:\/\/|https:\/\/).*/.";
        }

        if ($this->container['scope'] === null) {
            $invalidProperties[] = "'scope' can't be null";
        }
        if ((mb_strlen($this->container['scope']) > 256)) {
            $invalidProperties[] = "invalid value for 'scope', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['scope']) < 1)) {
            $invalidProperties[] = "invalid value for 'scope', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['tos_uri'] === null) {
            $invalidProperties[] = "'tos_uri' can't be null";
        }
        if ((mb_strlen($this->container['tos_uri']) > 256)) {
            $invalidProperties[] = "invalid value for 'tos_uri', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/^(http:\/\/|https:\/\/).*/", $this->container['tos_uri'])) {
            $invalidProperties[] = "invalid value for 'tos_uri', must be conform to the pattern /^(http:\/\/|https:\/\/).*/.";
        }

        if ($this->container['policy_uri'] === null) {
            $invalidProperties[] = "'policy_uri' can't be null";
        }
        if ((mb_strlen($this->container['policy_uri']) > 256)) {
            $invalidProperties[] = "invalid value for 'policy_uri', the character length must be smaller than or equal to 256.";
        }

        if (!preg_match("/^(http:\/\/|https:\/\/).*/", $this->container['policy_uri'])) {
            $invalidProperties[] = "invalid value for 'policy_uri', must be conform to the pattern /^(http:\/\/|https:\/\/).*/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets redirect_uris
     *
     * @return string[]
     */
    public function getRedirectUris()
    {
        return $this->container['redirect_uris'];
    }

    /**
     * Sets redirect_uris
     *
     * @param string[] $redirect_uris redirect_uris
     *
     * @return self
     */
    public function setRedirectUris($redirect_uris)
    {
        if (is_null($redirect_uris)) {
            throw new \InvalidArgumentException('non-nullable redirect_uris cannot be null');
        }
        $this->container['redirect_uris'] = $redirect_uris;

        return $this;
    }

    /**
     * Gets token_endpoint_auth_method
     *
     * @return string
     */
    public function getTokenEndpointAuthMethod()
    {
        return $this->container['token_endpoint_auth_method'];
    }

    /**
     * Sets token_endpoint_auth_method
     *
     * @param string $token_endpoint_auth_method token_endpoint_auth_method
     *
     * @return self
     */
    public function setTokenEndpointAuthMethod($token_endpoint_auth_method)
    {
        if (is_null($token_endpoint_auth_method)) {
            throw new \InvalidArgumentException('non-nullable token_endpoint_auth_method cannot be null');
        }
        if ((mb_strlen($token_endpoint_auth_method) > 256)) {
            throw new \InvalidArgumentException('invalid length for $token_endpoint_auth_method when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($token_endpoint_auth_method) < 1)) {
            throw new \InvalidArgumentException('invalid length for $token_endpoint_auth_method when calling OrganisationEnrol., must be bigger than or equal to 1.');
        }

        $this->container['token_endpoint_auth_method'] = $token_endpoint_auth_method;

        return $this;
    }

    /**
     * Gets grant_types
     *
     * @return string[]
     */
    public function getGrantTypes()
    {
        return $this->container['grant_types'];
    }

    /**
     * Sets grant_types
     *
     * @param string[] $grant_types grant_types
     *
     * @return self
     */
    public function setGrantTypes($grant_types)
    {
        if (is_null($grant_types)) {
            throw new \InvalidArgumentException('non-nullable grant_types cannot be null');
        }
        $this->container['grant_types'] = $grant_types;

        return $this;
    }

    /**
     * Gets response_types
     *
     * @return string[]
     */
    public function getResponseTypes()
    {
        return $this->container['response_types'];
    }

    /**
     * Sets response_types
     *
     * @param string[] $response_types response_types
     *
     * @return self
     */
    public function setResponseTypes($response_types)
    {
        if (is_null($response_types)) {
            throw new \InvalidArgumentException('non-nullable response_types cannot be null');
        }
        $this->container['response_types'] = $response_types;

        return $this;
    }

    /**
     * Gets client_name
     *
     * @return mixed
     */
    public function getClientName()
    {
        return $this->container['client_name'];
    }

    /**
     * Sets client_name
     *
     * @param mixed $client_name ORG name as per eIDAS certificate
     *
     * @return self
     */
    public function setClientName($client_name)
    {
        if (is_null($client_name)) {
            array_push($this->openAPINullablesSetToNull, 'client_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('client_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($client_name) && (mb_strlen($client_name) > 256)) {
            throw new \InvalidArgumentException('invalid length for $client_name when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if (!is_null($client_name) && (mb_strlen($client_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $client_name when calling OrganisationEnrol., must be bigger than or equal to 1.');
        }

        $this->container['client_name'] = $client_name;

        return $this;
    }

    /**
     * Gets client_uri
     *
     * @return string
     */
    public function getClientUri()
    {
        return $this->container['client_uri'];
    }

    /**
     * Sets client_uri
     *
     * @param string $client_uri A compliant URI
     *
     * @return self
     */
    public function setClientUri($client_uri)
    {
        if (is_null($client_uri)) {
            throw new \InvalidArgumentException('non-nullable client_uri cannot be null');
        }
        if ((mb_strlen($client_uri) > 256)) {
            throw new \InvalidArgumentException('invalid length for $client_uri when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/^(http:\/\/|https:\/\/).*/", ObjectSerializer::toString($client_uri)))) {
            throw new \InvalidArgumentException("invalid value for \$client_uri when calling OrganisationEnrol., must conform to the pattern /^(http:\/\/|https:\/\/).*/.");
        }

        $this->container['client_uri'] = $client_uri;

        return $this;
    }

    /**
     * Gets logo_uri
     *
     * @return string
     */
    public function getLogoUri()
    {
        return $this->container['logo_uri'];
    }

    /**
     * Sets logo_uri
     *
     * @param string $logo_uri A compliant URI
     *
     * @return self
     */
    public function setLogoUri($logo_uri)
    {
        if (is_null($logo_uri)) {
            throw new \InvalidArgumentException('non-nullable logo_uri cannot be null');
        }
        if ((mb_strlen($logo_uri) > 256)) {
            throw new \InvalidArgumentException('invalid length for $logo_uri when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/^(http:\/\/|https:\/\/).*/", ObjectSerializer::toString($logo_uri)))) {
            throw new \InvalidArgumentException("invalid value for \$logo_uri when calling OrganisationEnrol., must conform to the pattern /^(http:\/\/|https:\/\/).*/.");
        }

        $this->container['logo_uri'] = $logo_uri;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string $scope scope
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }
        if ((mb_strlen($scope) > 256)) {
            throw new \InvalidArgumentException('invalid length for $scope when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($scope) < 1)) {
            throw new \InvalidArgumentException('invalid length for $scope when calling OrganisationEnrol., must be bigger than or equal to 1.');
        }

        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets tos_uri
     *
     * @return string
     */
    public function getTosUri()
    {
        return $this->container['tos_uri'];
    }

    /**
     * Sets tos_uri
     *
     * @param string $tos_uri A compliant URI
     *
     * @return self
     */
    public function setTosUri($tos_uri)
    {
        if (is_null($tos_uri)) {
            throw new \InvalidArgumentException('non-nullable tos_uri cannot be null');
        }
        if ((mb_strlen($tos_uri) > 256)) {
            throw new \InvalidArgumentException('invalid length for $tos_uri when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/^(http:\/\/|https:\/\/).*/", ObjectSerializer::toString($tos_uri)))) {
            throw new \InvalidArgumentException("invalid value for \$tos_uri when calling OrganisationEnrol., must conform to the pattern /^(http:\/\/|https:\/\/).*/.");
        }

        $this->container['tos_uri'] = $tos_uri;

        return $this;
    }

    /**
     * Gets policy_uri
     *
     * @return string
     */
    public function getPolicyUri()
    {
        return $this->container['policy_uri'];
    }

    /**
     * Sets policy_uri
     *
     * @param string $policy_uri A compliant URI
     *
     * @return self
     */
    public function setPolicyUri($policy_uri)
    {
        if (is_null($policy_uri)) {
            throw new \InvalidArgumentException('non-nullable policy_uri cannot be null');
        }
        if ((mb_strlen($policy_uri) > 256)) {
            throw new \InvalidArgumentException('invalid length for $policy_uri when calling OrganisationEnrol., must be smaller than or equal to 256.');
        }
        if ((!preg_match("/^(http:\/\/|https:\/\/).*/", ObjectSerializer::toString($policy_uri)))) {
            throw new \InvalidArgumentException("invalid value for \$policy_uri when calling OrganisationEnrol., must conform to the pattern /^(http:\/\/|https:\/\/).*/.");
        }

        $this->container['policy_uri'] = $policy_uri;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


