<?php
/**
 * TreasureTitlesBalances
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Treasure Titles - Open Finance Brasil
 *
 * API de informações de operações de Títulos do Tesouro Direto Open Finance Brasil – Fase 4. API que retorna informações de operações de investimento do tipo Títulos do Tesouro Direto mantidas nas instituições transmissoras por seus clientes, incluindo dados como informações do produto, quantidade, saldos em posição do cliente e movimentações financeiras. Não possui segregação entre pessoa natural e pessoa jurídica. Requer consentimento do cliente para todos os endpoints. Devem ser considerados como escopo de exposição todos os títulos ofertados pelo Tesouro Direto. A exposição se dará por cada operação de títulos do Tesouro Direto contratada pelo cliente.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TreasureTitlesBalances Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TreasureTitlesBalances implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TreasureTitlesBalances';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'reference_date_time' => '\DateTime',
        'updated_unit_price' => '\OpenAPI\Client\Model\TreasureTitlesUpdatedUnitPrice',
        'gross_amount' => '\OpenAPI\Client\Model\TreasureTitlesGrossAmount',
        'net_amount' => '\OpenAPI\Client\Model\TreasureTitlesNetAmount',
        'income_tax' => '\OpenAPI\Client\Model\TreasureTitlesIncomeTax',
        'financial_transaction_tax' => '\OpenAPI\Client\Model\TreasureTitlesFinancialTransactionTax',
        'blocked_balance' => '\OpenAPI\Client\Model\TreasureTitlesBlockedBalance',
        'purchase_unit_price' => '\OpenAPI\Client\Model\TreasureTitlesPurchaseUnitPrice',
        'quantity' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'reference_date_time' => 'date-time',
        'updated_unit_price' => null,
        'gross_amount' => null,
        'net_amount' => null,
        'income_tax' => null,
        'financial_transaction_tax' => null,
        'blocked_balance' => null,
        'purchase_unit_price' => null,
        'quantity' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'reference_date_time' => false,
        'updated_unit_price' => false,
        'gross_amount' => false,
        'net_amount' => false,
        'income_tax' => false,
        'financial_transaction_tax' => false,
        'blocked_balance' => false,
        'purchase_unit_price' => false,
        'quantity' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reference_date_time' => 'referenceDateTime',
        'updated_unit_price' => 'updatedUnitPrice',
        'gross_amount' => 'grossAmount',
        'net_amount' => 'netAmount',
        'income_tax' => 'incomeTax',
        'financial_transaction_tax' => 'financialTransactionTax',
        'blocked_balance' => 'blockedBalance',
        'purchase_unit_price' => 'purchaseUnitPrice',
        'quantity' => 'quantity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reference_date_time' => 'setReferenceDateTime',
        'updated_unit_price' => 'setUpdatedUnitPrice',
        'gross_amount' => 'setGrossAmount',
        'net_amount' => 'setNetAmount',
        'income_tax' => 'setIncomeTax',
        'financial_transaction_tax' => 'setFinancialTransactionTax',
        'blocked_balance' => 'setBlockedBalance',
        'purchase_unit_price' => 'setPurchaseUnitPrice',
        'quantity' => 'setQuantity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reference_date_time' => 'getReferenceDateTime',
        'updated_unit_price' => 'getUpdatedUnitPrice',
        'gross_amount' => 'getGrossAmount',
        'net_amount' => 'getNetAmount',
        'income_tax' => 'getIncomeTax',
        'financial_transaction_tax' => 'getFinancialTransactionTax',
        'blocked_balance' => 'getBlockedBalance',
        'purchase_unit_price' => 'getPurchaseUnitPrice',
        'quantity' => 'getQuantity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('reference_date_time', $data ?? [], null);
        $this->setIfExists('updated_unit_price', $data ?? [], null);
        $this->setIfExists('gross_amount', $data ?? [], null);
        $this->setIfExists('net_amount', $data ?? [], null);
        $this->setIfExists('income_tax', $data ?? [], null);
        $this->setIfExists('financial_transaction_tax', $data ?? [], null);
        $this->setIfExists('blocked_balance', $data ?? [], null);
        $this->setIfExists('purchase_unit_price', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['reference_date_time'] === null) {
            $invalidProperties[] = "'reference_date_time' can't be null";
        }
        if ((mb_strlen($this->container['reference_date_time']) > 20)) {
            $invalidProperties[] = "invalid value for 'reference_date_time', the character length must be smaller than or equal to 20.";
        }

        if (!preg_match("/(^(\\d{4})-(1[0-2]|0?[1-9])-(3[01]|[12][0-9]|0?[1-9])T(?:[01]\\d|2[0123]):(?:[012345]\\d):(?:[012345]\\d)Z$)/", $this->container['reference_date_time'])) {
            $invalidProperties[] = "invalid value for 'reference_date_time', must be conform to the pattern /(^(\\d{4})-(1[0-2]|0?[1-9])-(3[01]|[12][0-9]|0?[1-9])T(?:[01]\\d|2[0123]):(?:[012345]\\d):(?:[012345]\\d)Z$)/.";
        }

        if ($this->container['updated_unit_price'] === null) {
            $invalidProperties[] = "'updated_unit_price' can't be null";
        }
        if ($this->container['gross_amount'] === null) {
            $invalidProperties[] = "'gross_amount' can't be null";
        }
        if ($this->container['net_amount'] === null) {
            $invalidProperties[] = "'net_amount' can't be null";
        }
        if ($this->container['income_tax'] === null) {
            $invalidProperties[] = "'income_tax' can't be null";
        }
        if ($this->container['blocked_balance'] === null) {
            $invalidProperties[] = "'blocked_balance' can't be null";
        }
        if ($this->container['purchase_unit_price'] === null) {
            $invalidProperties[] = "'purchase_unit_price' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ((mb_strlen($this->container['quantity']) > 24)) {
            $invalidProperties[] = "invalid value for 'quantity', the character length must be smaller than or equal to 24.";
        }

        if (!preg_match("/^\\d{1,15}\\.\\d{2,8}$/", $this->container['quantity'])) {
            $invalidProperties[] = "invalid value for 'quantity', must be conform to the pattern /^\\d{1,15}\\.\\d{2,8}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reference_date_time
     *
     * @return \DateTime
     */
    public function getReferenceDateTime()
    {
        return $this->container['reference_date_time'];
    }

    /**
     * Sets reference_date_time
     *
     * @param \DateTime $reference_date_time Data da última posição consolidada disponível a que se referem os dados transacionais do cliente disponíveis nos canais eletrônicos.
     *
     * @return self
     */
    public function setReferenceDateTime($reference_date_time)
    {
        if (is_null($reference_date_time)) {
            throw new \InvalidArgumentException('non-nullable reference_date_time cannot be null');
        }
        if ((mb_strlen($reference_date_time) > 20)) {
            throw new \InvalidArgumentException('invalid length for $reference_date_time when calling TreasureTitlesBalances., must be smaller than or equal to 20.');
        }
        if ((!preg_match("/(^(\\d{4})-(1[0-2]|0?[1-9])-(3[01]|[12][0-9]|0?[1-9])T(?:[01]\\d|2[0123]):(?:[012345]\\d):(?:[012345]\\d)Z$)/", ObjectSerializer::toString($reference_date_time)))) {
            throw new \InvalidArgumentException("invalid value for \$reference_date_time when calling TreasureTitlesBalances., must conform to the pattern /(^(\\d{4})-(1[0-2]|0?[1-9])-(3[01]|[12][0-9]|0?[1-9])T(?:[01]\\d|2[0123]):(?:[012345]\\d):(?:[012345]\\d)Z$)/.");
        }

        $this->container['reference_date_time'] = $reference_date_time;

        return $this;
    }

    /**
     * Gets updated_unit_price
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesUpdatedUnitPrice
     */
    public function getUpdatedUnitPrice()
    {
        return $this->container['updated_unit_price'];
    }

    /**
     * Sets updated_unit_price
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesUpdatedUnitPrice $updated_unit_price updated_unit_price
     *
     * @return self
     */
    public function setUpdatedUnitPrice($updated_unit_price)
    {
        if (is_null($updated_unit_price)) {
            throw new \InvalidArgumentException('non-nullable updated_unit_price cannot be null');
        }
        $this->container['updated_unit_price'] = $updated_unit_price;

        return $this;
    }

    /**
     * Gets gross_amount
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesGrossAmount
     */
    public function getGrossAmount()
    {
        return $this->container['gross_amount'];
    }

    /**
     * Sets gross_amount
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesGrossAmount $gross_amount gross_amount
     *
     * @return self
     */
    public function setGrossAmount($gross_amount)
    {
        if (is_null($gross_amount)) {
            throw new \InvalidArgumentException('non-nullable gross_amount cannot be null');
        }
        $this->container['gross_amount'] = $gross_amount;

        return $this;
    }

    /**
     * Gets net_amount
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesNetAmount
     */
    public function getNetAmount()
    {
        return $this->container['net_amount'];
    }

    /**
     * Sets net_amount
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesNetAmount $net_amount net_amount
     *
     * @return self
     */
    public function setNetAmount($net_amount)
    {
        if (is_null($net_amount)) {
            throw new \InvalidArgumentException('non-nullable net_amount cannot be null');
        }
        $this->container['net_amount'] = $net_amount;

        return $this;
    }

    /**
     * Gets income_tax
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesIncomeTax
     */
    public function getIncomeTax()
    {
        return $this->container['income_tax'];
    }

    /**
     * Sets income_tax
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesIncomeTax $income_tax income_tax
     *
     * @return self
     */
    public function setIncomeTax($income_tax)
    {
        if (is_null($income_tax)) {
            throw new \InvalidArgumentException('non-nullable income_tax cannot be null');
        }
        $this->container['income_tax'] = $income_tax;

        return $this;
    }

    /**
     * Gets financial_transaction_tax
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesFinancialTransactionTax|null
     */
    public function getFinancialTransactionTax()
    {
        return $this->container['financial_transaction_tax'];
    }

    /**
     * Sets financial_transaction_tax
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesFinancialTransactionTax|null $financial_transaction_tax financial_transaction_tax
     *
     * @return self
     */
    public function setFinancialTransactionTax($financial_transaction_tax)
    {
        if (is_null($financial_transaction_tax)) {
            throw new \InvalidArgumentException('non-nullable financial_transaction_tax cannot be null');
        }
        $this->container['financial_transaction_tax'] = $financial_transaction_tax;

        return $this;
    }

    /**
     * Gets blocked_balance
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesBlockedBalance
     */
    public function getBlockedBalance()
    {
        return $this->container['blocked_balance'];
    }

    /**
     * Sets blocked_balance
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesBlockedBalance $blocked_balance blocked_balance
     *
     * @return self
     */
    public function setBlockedBalance($blocked_balance)
    {
        if (is_null($blocked_balance)) {
            throw new \InvalidArgumentException('non-nullable blocked_balance cannot be null');
        }
        $this->container['blocked_balance'] = $blocked_balance;

        return $this;
    }

    /**
     * Gets purchase_unit_price
     *
     * @return \OpenAPI\Client\Model\TreasureTitlesPurchaseUnitPrice
     */
    public function getPurchaseUnitPrice()
    {
        return $this->container['purchase_unit_price'];
    }

    /**
     * Sets purchase_unit_price
     *
     * @param \OpenAPI\Client\Model\TreasureTitlesPurchaseUnitPrice $purchase_unit_price purchase_unit_price
     *
     * @return self
     */
    public function setPurchaseUnitPrice($purchase_unit_price)
    {
        if (is_null($purchase_unit_price)) {
            throw new \InvalidArgumentException('non-nullable purchase_unit_price cannot be null');
        }
        $this->container['purchase_unit_price'] = $purchase_unit_price;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float $quantity Quantidade de títulos detidos na data da posição do cliente.
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        if ((mb_strlen($quantity) > 24)) {
            throw new \InvalidArgumentException('invalid length for $quantity when calling TreasureTitlesBalances., must be smaller than or equal to 24.');
        }
        if ((!preg_match("/^\\d{1,15}\\.\\d{2,8}$/", ObjectSerializer::toString($quantity)))) {
            throw new \InvalidArgumentException("invalid value for \$quantity when calling TreasureTitlesBalances., must conform to the pattern /^\\d{1,15}\\.\\d{2,8}$/.");
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


