<?php
/**
 * BusinessCreditCardCompany
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API's OpenData do Open Finance Brasil
 *
 * As API's descritas neste documento são referentes as API's da fase OpenData do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BusinessCreditCardCompany Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BusinessCreditCardCompany implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BusinessCreditCardCompany';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cnpj_number' => 'string',
        'name' => 'string',
        'url_complementary_list' => 'string',
        'business_credit_cards' => '\OpenAPI\Client\Model\BusinessCreditCard[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cnpj_number' => null,
        'name' => null,
        'url_complementary_list' => null,
        'business_credit_cards' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cnpj_number' => false,
        'name' => false,
        'url_complementary_list' => false,
        'business_credit_cards' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cnpj_number' => 'cnpjNumber',
        'name' => 'name',
        'url_complementary_list' => 'urlComplementaryList',
        'business_credit_cards' => 'businessCreditCards'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cnpj_number' => 'setCnpjNumber',
        'name' => 'setName',
        'url_complementary_list' => 'setUrlComplementaryList',
        'business_credit_cards' => 'setBusinessCreditCards'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cnpj_number' => 'getCnpjNumber',
        'name' => 'getName',
        'url_complementary_list' => 'getUrlComplementaryList',
        'business_credit_cards' => 'getBusinessCreditCards'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cnpj_number', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('url_complementary_list', $data ?? [], null);
        $this->setIfExists('business_credit_cards', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cnpj_number'] === null) {
            $invalidProperties[] = "'cnpj_number' can't be null";
        }
        if ((mb_strlen($this->container['cnpj_number']) > 14)) {
            $invalidProperties[] = "invalid value for 'cnpj_number', the character length must be smaller than or equal to 14.";
        }

        if (!preg_match("/^(\\d{14})$|^NA$/", $this->container['cnpj_number'])) {
            $invalidProperties[] = "invalid value for 'cnpj_number', must be conform to the pattern /^(\\d{14})$|^NA$/.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 80)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 80.";
        }

        if (!preg_match("/\\w*\\W*/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /\\w*\\W*/.";
        }

        if (!is_null($this->container['url_complementary_list']) && (mb_strlen($this->container['url_complementary_list']) > 1024)) {
            $invalidProperties[] = "invalid value for 'url_complementary_list', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['url_complementary_list']) && !preg_match("/\\w*\\W*/", $this->container['url_complementary_list'])) {
            $invalidProperties[] = "invalid value for 'url_complementary_list', must be conform to the pattern /\\w*\\W*/.";
        }

        if (!is_null($this->container['business_credit_cards']) && (count($this->container['business_credit_cards']) < 1)) {
            $invalidProperties[] = "invalid value for 'business_credit_cards', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cnpj_number
     *
     * @return string
     */
    public function getCnpjNumber()
    {
        return $this->container['cnpj_number'];
    }

    /**
     * Sets cnpj_number
     *
     * @param string $cnpj_number CNPJ
     *
     * @return self
     */
    public function setCnpjNumber($cnpj_number)
    {
        if (is_null($cnpj_number)) {
            throw new \InvalidArgumentException('non-nullable cnpj_number cannot be null');
        }
        if ((mb_strlen($cnpj_number) > 14)) {
            throw new \InvalidArgumentException('invalid length for $cnpj_number when calling BusinessCreditCardCompany., must be smaller than or equal to 14.');
        }
        if ((!preg_match("/^(\\d{14})$|^NA$/", ObjectSerializer::toString($cnpj_number)))) {
            throw new \InvalidArgumentException("invalid value for \$cnpj_number when calling BusinessCreditCardCompany., must conform to the pattern /^(\\d{14})$|^NA$/.");
        }

        $this->container['cnpj_number'] = $cnpj_number;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Nome da Instituição, pertencente à marca, responsável pela modalidade de Empréstimos. p.ex.'Empresa da Organização A'
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 80)) {
            throw new \InvalidArgumentException('invalid length for $name when calling BusinessCreditCardCompany., must be smaller than or equal to 80.');
        }
        if ((!preg_match("/\\w*\\W*/", ObjectSerializer::toString($name)))) {
            throw new \InvalidArgumentException("invalid value for \$name when calling BusinessCreditCardCompany., must conform to the pattern /\\w*\\W*/.");
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets url_complementary_list
     *
     * @return string|null
     */
    public function getUrlComplementaryList()
    {
        return $this->container['url_complementary_list'];
    }

    /**
     * Sets url_complementary_list
     *
     * @param string|null $url_complementary_list URL do link que conterá a lista complementar com os nomes e CNPJs agrupados sob o mesmo cnpjNumber. Os contidos nessa lista possuem as mesmas características para produtos e serviços. Endereço eletrônico de acesso ao canal. Será obrigatoriamente preenchido se houver lista complementar com os nomes e CNPJs a ser disponibilizada. Restrição: Será obrigatorimente preenchido se houver lista complementar com os nomes e CNPJs a ser disponibilizada
     *
     * @return self
     */
    public function setUrlComplementaryList($url_complementary_list)
    {
        if (is_null($url_complementary_list)) {
            throw new \InvalidArgumentException('non-nullable url_complementary_list cannot be null');
        }
        if ((mb_strlen($url_complementary_list) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $url_complementary_list when calling BusinessCreditCardCompany., must be smaller than or equal to 1024.');
        }
        if ((!preg_match("/\\w*\\W*/", ObjectSerializer::toString($url_complementary_list)))) {
            throw new \InvalidArgumentException("invalid value for \$url_complementary_list when calling BusinessCreditCardCompany., must conform to the pattern /\\w*\\W*/.");
        }

        $this->container['url_complementary_list'] = $url_complementary_list;

        return $this;
    }

    /**
     * Gets business_credit_cards
     *
     * @return \OpenAPI\Client\Model\BusinessCreditCard[]|null
     */
    public function getBusinessCreditCards()
    {
        return $this->container['business_credit_cards'];
    }

    /**
     * Sets business_credit_cards
     *
     * @param \OpenAPI\Client\Model\BusinessCreditCard[]|null $business_credit_cards Lista dos nomes de conta de pagamento pós-paga
     *
     * @return self
     */
    public function setBusinessCreditCards($business_credit_cards)
    {
        if (is_null($business_credit_cards)) {
            throw new \InvalidArgumentException('non-nullable business_credit_cards cannot be null');
        }


        if ((count($business_credit_cards) < 1)) {
            throw new \InvalidArgumentException('invalid length for $business_credit_cards when calling BusinessCreditCardCompany., number of items must be greater than or equal to 1.');
        }
        $this->container['business_credit_cards'] = $business_credit_cards;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


