<?php
/**
 * EnumInvestmentsFundFeesPerformanceFeeMethod
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Investments - Open Finance Brasil
 *
 * Estas APIs visam o compartilhamento de dados sobre Investimentos e suas características entre as Instituições Financeiras participantes do Open Finance Brasil
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EnumInvestmentsFundFeesPerformanceFeeMethod Class Doc Comment
 *
 * @category Class
 * @description Metodologia do campo para taxa de performance.&lt;br&gt;&lt;ol&gt;&lt;li&gt;Passivo&lt;/li&gt;&lt;li&gt;Ativo&lt;/li&gt;&lt;li&gt;Ajuste&lt;/li&gt;&lt;/ol&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnumInvestmentsFundFeesPerformanceFeeMethod
{
    /**
     * Possible values of this enum
     */
    public const PASSIVO = 'PASSIVO';

    public const ATIVO = 'ATIVO';

    public const AJUSTE = 'AJUSTE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PASSIVO,
            self::ATIVO,
            self::AJUSTE
        ];
    }
}


