<?php
/**
 * EnumInterval
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Investments - Open Finance Brasil
 *
 * Estas APIs visam o compartilhamento de dados sobre Investimentos e suas características entre as Instituições Financeiras participantes do Open Finance Brasil
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EnumInterval Class Doc Comment
 *
 * @category Class
 * @description Faixas de frequência
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnumInterval
{
    /**
     * Possible values of this enum
     */
    public const _1_FAIXA = '1_FAIXA';

    public const _2_FAIXA = '2_FAIXA';

    public const _3_FAIXA = '3_FAIXA';

    public const _4_FAIXA = '4_FAIXA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_1_FAIXA,
            self::_2_FAIXA,
            self::_3_FAIXA,
            self::_4_FAIXA
        ];
    }
}


