<?php
/**
 * CapitalizationBondsProductQuotaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Capitalization-bonds - Open Finance Brasil
 *
 * As APIs descritas neste documento é referente a API de Capitalização da fase OpenInsurance do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CapitalizationBondsProductQuotaTest Class Doc Comment
 *
 * @category    Class
 * @description CapitalizationBondsProductQuota
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CapitalizationBondsProductQuotaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CapitalizationBondsProductQuota"
     */
    public function testCapitalizationBondsProductQuota()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quota"
     */
    public function testPropertyQuota()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "capitalization_quota"
     */
    public function testPropertyCapitalizationQuota()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "raffle_quota"
     */
    public function testPropertyRaffleQuota()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "charging_quota"
     */
    public function testPropertyChargingQuota()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
