<?php
/**
 * CapitalizationBondsProductCapitalizationPeriodTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Capitalization-bonds - Open Finance Brasil
 *
 * As APIs descritas neste documento é referente a API de Capitalização da fase OpenInsurance do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CapitalizationBondsProductCapitalizationPeriodTest Class Doc Comment
 *
 * @category    Class
 * @description Informações relativas ao período de capitalização.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CapitalizationBondsProductCapitalizationPeriodTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CapitalizationBondsProductCapitalizationPeriod"
     */
    public function testCapitalizationBondsProductCapitalizationPeriod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "interest_rate"
     */
    public function testPropertyInterestRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "update_index"
     */
    public function testPropertyUpdateIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "update_index_additional_info"
     */
    public function testPropertyUpdateIndexAdditionalInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contribution_amount"
     */
    public function testPropertyContributionAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "early_redemptions"
     */
    public function testPropertyEarlyRedemptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "redemption_percentage_end_term"
     */
    public function testPropertyRedemptionPercentageEndTerm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "grace_period_redemption"
     */
    public function testPropertyGracePeriodRedemption()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
