<?php
/**
 * Participant
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Exchange - Open Finance Brasil
 *
 * API de Câmbio do Open Finance Brasil – Fase 4. API que retorna informações de Câmbio.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Participant Class Doc Comment
 *
 * @category Class
 * @description Conjunto de informações relativas ao participante do produto de Open Finance
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Participant implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Participant';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'brand' => 'string',
        'name' => 'string',
        'cnpj_number' => 'string',
        'url_complementary_list' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'brand' => null,
        'name' => null,
        'cnpj_number' => null,
        'url_complementary_list' => 'url'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'brand' => false,
        'name' => false,
        'cnpj_number' => false,
        'url_complementary_list' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'brand' => 'brand',
        'name' => 'name',
        'cnpj_number' => 'cnpjNumber',
        'url_complementary_list' => 'urlComplementaryList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'brand' => 'setBrand',
        'name' => 'setName',
        'cnpj_number' => 'setCnpjNumber',
        'url_complementary_list' => 'setUrlComplementaryList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'brand' => 'getBrand',
        'name' => 'getName',
        'cnpj_number' => 'getCnpjNumber',
        'url_complementary_list' => 'getUrlComplementaryList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('brand', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('cnpj_number', $data ?? [], null);
        $this->setIfExists('url_complementary_list', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['brand'] === null) {
            $invalidProperties[] = "'brand' can't be null";
        }
        if ((mb_strlen($this->container['brand']) > 80)) {
            $invalidProperties[] = "invalid value for 'brand', the character length must be smaller than or equal to 80.";
        }

        if (!preg_match("/[\\w\\W\\s]*/", $this->container['brand'])) {
            $invalidProperties[] = "invalid value for 'brand', must be conform to the pattern /[\\w\\W\\s]*/.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 80)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 80.";
        }

        if (!preg_match("/[\\w\\W\\s]*/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /[\\w\\W\\s]*/.";
        }

        if ($this->container['cnpj_number'] === null) {
            $invalidProperties[] = "'cnpj_number' can't be null";
        }
        if ((mb_strlen($this->container['cnpj_number']) > 14)) {
            $invalidProperties[] = "invalid value for 'cnpj_number', the character length must be smaller than or equal to 14.";
        }

        if (!preg_match("/^\\d{14}$/", $this->container['cnpj_number'])) {
            $invalidProperties[] = "invalid value for 'cnpj_number', must be conform to the pattern /^\\d{14}$/.";
        }

        if (!is_null($this->container['url_complementary_list']) && (mb_strlen($this->container['url_complementary_list']) > 1024)) {
            $invalidProperties[] = "invalid value for 'url_complementary_list', the character length must be smaller than or equal to 1024.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets brand
     *
     * @return string
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string $brand Nome da marca reportada pelo participante do Open Finance. O conceito a que se refere a 'marca' é em essência uma promessa da empresa em fornecer uma série específica de atributos, benefícios e serviços uniformes aos clientes.
     *
     * @return self
     */
    public function setBrand($brand)
    {
        if (is_null($brand)) {
            throw new \InvalidArgumentException('non-nullable brand cannot be null');
        }
        if ((mb_strlen($brand) > 80)) {
            throw new \InvalidArgumentException('invalid length for $brand when calling Participant., must be smaller than or equal to 80.');
        }
        if ((!preg_match("/[\\w\\W\\s]*/", ObjectSerializer::toString($brand)))) {
            throw new \InvalidArgumentException("invalid value for \$brand when calling Participant., must conform to the pattern /[\\w\\W\\s]*/.");
        }

        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Nome do participante do Open Finance.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 80)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Participant., must be smaller than or equal to 80.');
        }
        if ((!preg_match("/[\\w\\W\\s]*/", ObjectSerializer::toString($name)))) {
            throw new \InvalidArgumentException("invalid value for \$name when calling Participant., must conform to the pattern /[\\w\\W\\s]*/.");
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets cnpj_number
     *
     * @return string
     */
    public function getCnpjNumber()
    {
        return $this->container['cnpj_number'];
    }

    /**
     * Sets cnpj_number
     *
     * @param string $cnpj_number O CNPJ corresponde ao número de inscrição no Cadastro de Pessoa Jurídica. Deve-se ter apenas os números do CNPJ, sem máscara.
     *
     * @return self
     */
    public function setCnpjNumber($cnpj_number)
    {
        if (is_null($cnpj_number)) {
            throw new \InvalidArgumentException('non-nullable cnpj_number cannot be null');
        }
        if ((mb_strlen($cnpj_number) > 14)) {
            throw new \InvalidArgumentException('invalid length for $cnpj_number when calling Participant., must be smaller than or equal to 14.');
        }
        if ((!preg_match("/^\\d{14}$/", ObjectSerializer::toString($cnpj_number)))) {
            throw new \InvalidArgumentException("invalid value for \$cnpj_number when calling Participant., must conform to the pattern /^\\d{14}$/.");
        }

        $this->container['cnpj_number'] = $cnpj_number;

        return $this;
    }

    /**
     * Gets url_complementary_list
     *
     * @return string|null
     */
    public function getUrlComplementaryList()
    {
        return $this->container['url_complementary_list'];
    }

    /**
     * Sets url_complementary_list
     *
     * @param string|null $url_complementary_list Espera-se que valor de retorno, após acesso ao link ‘urlComplementaryList’, deve ser array de objeto com a estrutura abaixo:  - ‘name’ com o valor contido no campo ‘LegalEntityName’ conforme cadastro no diretório;  - 'cnpjNumber' com o valor contido no campo CNPJ (‘RegistrationNumber’) correspondente a esta instituição;  - Ambos do tipo string;  - Ambos obrigatórios.
     *
     * @return self
     */
    public function setUrlComplementaryList($url_complementary_list)
    {
        if (is_null($url_complementary_list)) {
            throw new \InvalidArgumentException('non-nullable url_complementary_list cannot be null');
        }
        if ((mb_strlen($url_complementary_list) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $url_complementary_list when calling Participant., must be smaller than or equal to 1024.');
        }

        $this->container['url_complementary_list'] = $url_complementary_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


