<?php
/**
 * BankingAgentIdentificationTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIs OpenData do Open Finance Brasil
 *
 * As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BankingAgentIdentificationTest Class Doc Comment
 *
 * @category    Class
 * @description BankingAgentIdentification
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UchannelsBankingAgentIdentificationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BankingAgentIdentification"
     */
    public function testBankingAgentIdentification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnpj_number"
     */
    public function testPropertyCnpjNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "corporation_name"
     */
    public function testPropertyCorporationName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_underestablishment"
     */
    public function testPropertyIsUnderestablishment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
