<?php
/**
 * RiskPensionEnumContributionPaymentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Pension - Open Finance Brasil
 *
 * API de Previdência do Open Finance Brasil – Fase 4. API que retorna informações de Previdência.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RiskPensionEnumContributionPaymentTest Class Doc Comment
 *
 * @category    Class
 * @description Pagamento da contribuição.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpensionRiskPensionEnumContributionPaymentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RiskPensionEnumContributionPayment"
     */
    public function testRiskPensionEnumContributionPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contribution_payment_method"
     */
    public function testPropertyContributionPaymentMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contribution_payment_method_additional_info"
     */
    public function testPropertyContributionPaymentMethodAdditionalInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contribution_periodicity"
     */
    public function testPropertyContributionPeriodicity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contribution_periodicity_additional_info"
     */
    public function testPropertyContributionPeriodicityAdditionalInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
