<?php
/**
 * RiskPensionEnumPmbacRemuneration
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Pension - Open Finance Brasil
 *
 * API de Previdência do Open Finance Brasil – Fase 4. API que retorna informações de Previdência.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: gt-interfaces@openbankingbr.org
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RiskPensionEnumPmbacRemuneration Class Doc Comment
 *
 * @category Class
 * @description Atualização/ Remuneração da PMBaC
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RiskPensionEnumPmbacRemuneration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RiskPensionEnumPmbacRemuneration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'interest_rate' => 'string',
        'update_indexes' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'interest_rate' => null,
        'update_indexes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'interest_rate' => false,
        'update_indexes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'interest_rate' => 'interestRate',
        'update_indexes' => 'updateIndexes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'interest_rate' => 'setInterestRate',
        'update_indexes' => 'setUpdateIndexes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'interest_rate' => 'getInterestRate',
        'update_indexes' => 'getUpdateIndexes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const UPDATE_INDEXES_IPCA = 'IPCA';
    public const UPDATE_INDEXES_IGP_M = 'IGP_M';
    public const UPDATE_INDEXES_INPC = 'INPC';
    public const UPDATE_INDEXES_NA = 'NA';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUpdateIndexesAllowableValues()
    {
        return [
            self::UPDATE_INDEXES_IPCA,
            self::UPDATE_INDEXES_IGP_M,
            self::UPDATE_INDEXES_INPC,
            self::UPDATE_INDEXES_NA,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('interest_rate', $data ?? [], null);
        $this->setIfExists('update_indexes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['interest_rate'] === null) {
            $invalidProperties[] = "'interest_rate' can't be null";
        }
        if ((mb_strlen($this->container['interest_rate']) > 9)) {
            $invalidProperties[] = "invalid value for 'interest_rate', the character length must be smaller than or equal to 9.";
        }

        if ((mb_strlen($this->container['interest_rate']) < 8)) {
            $invalidProperties[] = "invalid value for 'interest_rate', the character length must be bigger than or equal to 8.";
        }

        if (!preg_match("/^(\\d{1}\\.\\d{6})$|^(-1.000000)$/", $this->container['interest_rate'])) {
            $invalidProperties[] = "invalid value for 'interest_rate', must be conform to the pattern /^(\\d{1}\\.\\d{6})$|^(-1.000000)$/.";
        }

        if (!is_null($this->container['update_indexes']) && (count($this->container['update_indexes']) > 2147483647)) {
            $invalidProperties[] = "invalid value for 'update_indexes', number of items must be less than or equal to 2147483647.";
        }

        if (!is_null($this->container['update_indexes']) && (count($this->container['update_indexes']) < 0)) {
            $invalidProperties[] = "invalid value for 'update_indexes', number of items must be greater than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets interest_rate
     *
     * @return string
     */
    public function getInterestRate()
    {
        return $this->container['interest_rate'];
    }

    /**
     * Sets interest_rate
     *
     * @param string $interest_rate Taxa de juros para capitalização da PMBaC
     *
     * @return self
     */
    public function setInterestRate($interest_rate)
    {
        if (is_null($interest_rate)) {
            throw new \InvalidArgumentException('non-nullable interest_rate cannot be null');
        }
        if ((mb_strlen($interest_rate) > 9)) {
            throw new \InvalidArgumentException('invalid length for $interest_rate when calling RiskPensionEnumPmbacRemuneration., must be smaller than or equal to 9.');
        }
        if ((mb_strlen($interest_rate) < 8)) {
            throw new \InvalidArgumentException('invalid length for $interest_rate when calling RiskPensionEnumPmbacRemuneration., must be bigger than or equal to 8.');
        }
        if ((!preg_match("/^(\\d{1}\\.\\d{6})$|^(-1.000000)$/", ObjectSerializer::toString($interest_rate)))) {
            throw new \InvalidArgumentException("invalid value for \$interest_rate when calling RiskPensionEnumPmbacRemuneration., must conform to the pattern /^(\\d{1}\\.\\d{6})$|^(-1.000000)$/.");
        }

        $this->container['interest_rate'] = $interest_rate;

        return $this;
    }

    /**
     * Gets update_indexes
     *
     * @return string[]|null
     */
    public function getUpdateIndexes()
    {
        return $this->container['update_indexes'];
    }

    /**
     * Sets update_indexes
     *
     * @param string[]|null $update_indexes Índice utilizado na atualização da PMBaC
     *
     * @return self
     */
    public function setUpdateIndexes($update_indexes)
    {
        if (is_null($update_indexes)) {
            throw new \InvalidArgumentException('non-nullable update_indexes cannot be null');
        }
        $allowedValues = $this->getUpdateIndexesAllowableValues();
        if (array_diff($update_indexes, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'update_indexes', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        if ((count($update_indexes) > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $update_indexes when calling RiskPensionEnumPmbacRemuneration., number of items must be less than or equal to 2147483647.');
        }
        if ((count($update_indexes) < 0)) {
            throw new \InvalidArgumentException('invalid length for $update_indexes when calling RiskPensionEnumPmbacRemuneration., number of items must be greater than or equal to 0.');
        }
        $this->container['update_indexes'] = $update_indexes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


